// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "test-stag",
            "region": "eu-west-1"
        },
        {
            "tableName": "test2-stag",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:ad4744db-006d-4169-b476-9de6170d3baa",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_JGkIKeItC",
    "aws_user_pools_web_client_id": "n3q40q8k7itj0o6t47an0594j",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "testApi",
            "endpoint": "https://vdu4e13gq4.execute-api.eu-west-1.amazonaws.com/stag",
            "region": "eu-west-1"
        }
    ]
};


module.exports = awsmobile;
